name: marketplace_logamas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.6.3
  intl: ^0.20.1
  flutter_map: ^7.0.2
  geolocator: ^13.0.2
  http: ^1.2.2
  smooth_page_indicator: ^1.2.0+3
  latlong2: ^0.9.1
  url_launcher: ^6.3.1
  shared_preferences: ^2.3.3
  # midtrans_sdk: ^0.4.0
  shimmer: ^3.0.0
  webview_flutter: ^4.10.0
  cached_network_image: ^3.4.1
  qr_flutter: ^4.1.0
  barcode: ^2.2.8
  flutter_svg: ^2.0.16
  firebase_core: ^3.10.0
  firebase_messaging: ^15.2.0
  fl_chart: ^0.70.2
  dot_navigation_bar: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/empty_cart.png
